name: ta2025
channels:
  - defaults
dependencies:
  - jupyter
  - nltk
  - numpy
  - pandas
  - pip
  - python=3.13
  - qrcode
  - scikit-learn
  - scipy
  - seaborn
  - yaml
  - pip:
      - gensim
      - manim
      - openai
      - plotly
      - spacy
      - torch
      - transformers
